import { Cliente, Tarefa, Lead, MembroTime } from '../types'

export const mockClientes: Cliente[] = [
    {
        id: 'c1',
        nome: 'Bella Moda',
        site: 'bellamoda.com.br',
        tipo: 'E-commerce',
        status: 'Ativo',
        investimento_mensal: 8000,
        conta_meta_ads: 'bellamoda_meta',
        conta_google_ads: 'bellamoda_gads',
        meta_faturamento: 120000,
        faturado_ate_data: 108500,
        responsaveis: ['Rodrigo', 'Ana'],
        contrato_mensal: 5500,
        vigencia_inicio: '2025-01-01',
        vigencia_fim: '2025-12-31',
        nps: 9,
        criado_em: '2025-01-01',
    },
    {
        id: 'c2',
        nome: 'Dr. Rafael Odonto',
        site: 'drrafaeodonto.com.br',
        tipo: 'Negócio Local',
        status: 'Ativo',
        investimento_mensal: 3500,
        conta_meta_ads: 'drrafael_meta',
        conta_google_ads: '',
        meta_faturamento: 45000,
        faturado_ate_data: 29000,
        responsaveis: ['Ana'],
        contrato_mensal: 2800,
        vigencia_inicio: '2025-03-01',
        vigencia_fim: '2026-02-28',
        nps: 7,
        criado_em: '2025-03-01',
    },
    {
        id: 'c3',
        nome: 'Curso Mentalidade Rica',
        site: 'mentalidaderica.com.br',
        tipo: 'Info Produto',
        status: 'Ativo',
        investimento_mensal: 15000,
        conta_meta_ads: 'mentalidade_meta',
        conta_google_ads: 'mentalidade_gads',
        meta_faturamento: 250000,
        faturado_ate_data: 130000,
        responsaveis: ['Rodrigo'],
        contrato_mensal: 9800,
        vigencia_inicio: '2025-02-01',
        vigencia_fim: '2025-07-31',
        nps: 5,
        criado_em: '2025-02-01',
    },
    {
        id: 'c4',
        nome: 'Pet Gourmet',
        site: 'petgourmet.com.br',
        tipo: 'E-commerce',
        status: 'Prospectando',
        investimento_mensal: 0,
        conta_meta_ads: '',
        conta_google_ads: '',
        meta_faturamento: 60000,
        faturado_ate_data: 0,
        responsaveis: ['Rodrigo'],
        contrato_mensal: 0,
        nps: undefined,
        criado_em: '2026-02-20',
    },
    {
        id: 'c5',
        nome: 'TechFix Assistência',
        site: 'techfix.net.br',
        tipo: 'Negócio Local',
        status: 'Encerrado',
        investimento_mensal: 2000,
        conta_meta_ads: 'techfix_meta',
        conta_google_ads: '',
        meta_faturamento: 30000,
        faturado_ate_data: 18000,
        responsaveis: ['Ana'],
        contrato_mensal: 1800,
        vigencia_inicio: '2024-06-01',
        vigencia_fim: '2024-12-31',
        nps: 6,
        criado_em: '2024-06-01',
    },
]

// Today reference for due dates: 2026-03-05
export const mockTarefas: Tarefa[] = [
    {
        id: 't1',
        titulo: 'Criar criativos para campanha de Março',
        descricao: 'Produzir 5 artes para feed e 3 stories com o tema "Primavera".',
        cliente_id: 'c1',
        cliente_nome: 'Bella Moda',
        solicitante: 'Rodrigo',
        responsavel: 'Ana',
        prioridade: 'alta',
        status: 'Em Andamento',
        data_vencimento: '2026-03-08',
        recorrencia: 'não',
    },
    {
        id: 't2',
        titulo: 'Relatório mensal — Fevereiro',
        descricao: 'Compilar métricas de Meta Ads e Google Ads do mês anterior.',
        cliente_id: 'c1',
        cliente_nome: 'Bella Moda',
        solicitante: 'Rodrigo',
        responsavel: 'Rodrigo',
        prioridade: 'média',
        status: 'A Fazer',
        data_vencimento: '2026-03-03',
        recorrencia: 'mensal',
    },
    {
        id: 't3',
        titulo: 'Otimização de campanhas Google',
        descricao: 'Revisar palavras-chave e ajustar lances.',
        cliente_id: 'c3',
        cliente_nome: 'Curso Mentalidade Rica',
        solicitante: 'Rodrigo',
        responsavel: 'Rodrigo',
        prioridade: 'alta',
        status: 'A Fazer',
        data_vencimento: '2026-02-28',
        recorrencia: 'semanal',
    },
    {
        id: 't4',
        titulo: 'Reunião de alinhamento',
        descricao: 'Call mensal de alinhamento estratégico.',
        cliente_id: 'c2',
        cliente_nome: 'Dr. Rafael Odonto',
        solicitante: 'Ana',
        responsavel: 'Rodrigo',
        prioridade: 'média',
        status: 'A Fazer',
        data_vencimento: '2026-03-10',
        recorrencia: 'mensal',
    },
    {
        id: 't5',
        titulo: 'Revisão da landing page',
        descricao: 'Checar copy e CTA da página principal.',
        cliente_id: 'c3',
        cliente_nome: 'Curso Mentalidade Rica',
        solicitante: 'Rodrigo',
        responsavel: 'Ana',
        prioridade: 'baixa',
        status: 'Em Revisão',
        data_vencimento: '2026-03-12',
        recorrencia: 'não',
    },
    {
        id: 't6',
        titulo: 'Configurar pixel Meta Ads',
        descricao: 'Instalar e verificar o pixel de conversão.',
        cliente_id: 'c2',
        cliente_nome: 'Dr. Rafael Odonto',
        solicitante: 'Ana',
        responsavel: 'Ana',
        prioridade: 'alta',
        status: 'Concluído',
        data_vencimento: '2026-02-25',
        recorrencia: 'não',
    },
    {
        id: 't7',
        titulo: 'Publicação semanal de conteúdo',
        descricao: 'Postar 4 conteúdos educativos no feed.',
        cliente_id: 'c3',
        cliente_nome: 'Curso Mentalidade Rica',
        solicitante: 'Rodrigo',
        responsavel: 'Ana',
        prioridade: 'média',
        status: 'Concluído',
        data_vencimento: '2026-03-01',
        recorrencia: 'semanal',
    },
    {
        id: 't8',
        titulo: 'Proposta comercial — Pet Gourmet',
        descricao: 'Montar proposta de gestão de tráfego pago.',
        cliente_id: 'c4',
        cliente_nome: 'Pet Gourmet',
        solicitante: 'Rodrigo',
        responsavel: 'Rodrigo',
        prioridade: 'alta',
        status: 'Em Andamento',
        data_vencimento: '2026-03-06',
        recorrencia: 'não',
    },
    {
        id: 't9',
        titulo: 'Análise de concorrentes',
        descricao: 'Mapear estratégias dos principais concorrentes.',
        cliente_id: 'c1',
        cliente_nome: 'Bella Moda',
        solicitante: 'Rodrigo',
        responsavel: 'Ana',
        prioridade: 'baixa',
        status: 'A Fazer',
        data_vencimento: '2026-03-20',
        recorrencia: 'quinzenal',
    },
    {
        id: 't10',
        titulo: 'Campanha Dia das Mulheres',
        descricao: 'Planejar e subir campanha temática para 8 de Março.',
        cliente_id: 'c1',
        cliente_nome: 'Bella Moda',
        solicitante: 'Rodrigo',
        responsavel: 'Rodrigo',
        prioridade: 'alta',
        status: 'Em Andamento',
        data_vencimento: '2026-03-07',
        recorrencia: 'não',
    },
]

export const mockLeads: Lead[] = [
    {
        id: 'l1',
        empresa: 'Clínica VidaBem',
        contato: 'Dr. Marcos — (11) 98888-1111',
        valor_estimado: 3500,
        origem: 'Indicação',
        notas: 'Interessado em gestão de Instagram e Google Meu Negócio.',
        status: 'Leads',
        criado_em: '2026-02-28',
    },
    {
        id: 'l2',
        empresa: 'Academia FitForce',
        contato: 'Carla Souza — (21) 97777-2222',
        valor_estimado: 2800,
        origem: 'Instagram',
        notas: 'Quer aumentar matrículas com Meta Ads.',
        status: 'Contato Feito',
        criado_em: '2026-02-20',
    },
    {
        id: 'l3',
        empresa: 'Imobiliária Sol Nascente',
        contato: 'Paulo Andrade — (41) 96666-3333',
        valor_estimado: 6000,
        origem: 'LinkedIn',
        notas: 'Grande demanda por tráfego pago para imóveis de alto padrão.',
        status: 'Proposta Enviada',
        criado_em: '2026-02-15',
    },
    {
        id: 'l4',
        empresa: 'Padaria Artesanal Grão',
        contato: 'Juliana Reis — (31) 95555-4444',
        valor_estimado: 1800,
        origem: 'Indicação',
        notas: 'Quer delivery e engajamento local.',
        status: 'Negociação',
        criado_em: '2026-02-10',
    },
    {
        id: 'l5',
        empresa: 'Fintech Credinova',
        contato: 'Roberto Lima — (11) 94444-5555',
        valor_estimado: 12000,
        origem: 'Evento',
        notas: 'Fechado após proposta de gestão completa.',
        status: 'Fechado',
        criado_em: '2026-01-20',
    },
    {
        id: 'l6',
        empresa: 'Restaurante Sabor Certo',
        contato: 'Fernanda Costa — (19) 93333-6666',
        valor_estimado: 2000,
        origem: 'Google',
        notas: 'Orçamento fora do esperado.',
        status: 'Perdido',
        criado_em: '2026-01-15',
    },
]

export const mockMembros: MembroTime[] = [
    {
        id: 'm1',
        nome: 'Rodrigo Carvalho',
        funcao: 'CEO & Estrategista de Tráfego',
        telefone: '(11) 99999-0001',
        foto_url: '',
    },
    {
        id: 'm2',
        nome: 'Ana Paula',
        funcao: 'Gestora de Tráfego',
        telefone: '(11) 99999-0002',
        foto_url: '',
    },
    {
        id: 'm3',
        nome: 'Lucas Mendes',
        funcao: 'Designer Gráfico',
        telefone: '(11) 99999-0003',
        foto_url: '',
    },
    {
        id: 'm4',
        nome: 'Camila Torres',
        funcao: 'Copywriter',
        telefone: '(11) 99999-0004',
        foto_url: '',
    },
]
